---
abstract: 'Modify a Perl distribution to make it portable'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  File::Copy::Recursive: 0.35
  File::Remove: 1.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Portable::Dist
name: Portable-Dist
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Find::Rule: 0.30
  File::IgnoreReadonly: 0.01
  File::Slurp: 9999.13
  File::Spec: 0.80
  File::chmod: 0.32
  Object::Tiny: 1.04
  Params::Util: 0.31
  Tie::Slurp: 0.03
  perl: 5.8.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Portable-Dist
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Portable-Dist
version: 1.04
